from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
FRONTEND_SRC = ROOT / "frontend" / "src"


class FrontendTemplateSlotSourceTest(unittest.TestCase):
    def test_client_exposes_record_template_slot_api(self) -> None:
        client_source = (FRONTEND_SRC / "api" / "client.ts").read_text(encoding="utf-8")

        self.assertIn("export type RecordTemplateSlot", client_source)
        self.assertIn("export function getRecordTemplateSlots", client_source)
        self.assertIn("/api/record-template-slots", client_source)

    def test_client_exposes_record_template_slot_update_reset_and_backup(self) -> None:
        client_source = (FRONTEND_SRC / "api" / "client.ts").read_text(encoding="utf-8")

        self.assertIn("export type RecordTemplateSlotUpdateInput", client_source)
        self.assertIn("export type RecordTemplateSlotImportPayload", client_source)
        self.assertIn("export function updateRecordTemplateSlot", client_source)
        self.assertIn("export function resetRecordTemplateSlot", client_source)
        self.assertIn("export function exportRecordTemplateSlots", client_source)
        self.assertIn("export function previewRecordTemplateSlotImport", client_source)
        self.assertIn("export function importRecordTemplateSlots", client_source)
        self.assertIn("method: \"PUT\"", client_source)
        self.assertIn("/reset", client_source)
        self.assertIn("/api/record-template-slots/export", client_source)
        self.assertIn("/api/record-template-slots/import-preview", client_source)
        self.assertIn("/api/record-template-slots/import", client_source)

    def test_project_page_loads_slots_for_active_section(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")

        self.assertIn("getRecordTemplateSlots", page_source)
        self.assertIn("refreshRecordTemplateSlots(activeCode)", page_source)
        self.assertIn("recordTemplateSlots={activeRecordTemplateSlots}", page_source)

    def test_project_page_wires_template_manager_to_slot_editor(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")

        self.assertIn("updateRecordTemplateSlot", page_source)
        self.assertIn("resetRecordTemplateSlot", page_source)
        self.assertIn("exportRecordTemplateSlots", page_source)
        self.assertIn("previewRecordTemplateSlotImport", page_source)
        self.assertIn("importRecordTemplateSlots", page_source)
        self.assertIn("recordTemplateSlots={recordTemplateSlots}", page_source)
        self.assertIn("onUpdateSlot={handleUpdateRecordTemplateSlot}", page_source)
        self.assertIn("onResetSlot={handleResetRecordTemplateSlot}", page_source)
        self.assertIn("onExportSlots={handleExportRecordTemplateSlots}", page_source)
        self.assertIn("onPreviewImportSlots={handlePreviewRecordTemplateSlotImport}", page_source)
        self.assertIn("onImportSlots={handleImportRecordTemplateSlots}", page_source)
        self.assertNotIn("handleSaveRowAsTemplate", page_source)
        self.assertNotIn("handleCreateRecordTemplate", page_source)
        self.assertNotIn("handleDeleteRecordTemplate", page_source)
        self.assertNotIn("handleCopyRecordTemplate", page_source)

    def test_project_page_removes_render_preview_entry(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")

        self.assertNotIn("createRenderJob", page_source)
        self.assertNotIn("getRenderJob", page_source)
        self.assertNotIn("type RenderJob", page_source)
        self.assertNotIn("isCreatingPreview", page_source)
        self.assertNotIn("renderJob", page_source)
        self.assertNotIn("handleCreatePreview", page_source)
        self.assertNotIn("function PreviewPanel", page_source)
        self.assertNotIn("renderJob ? <PreviewPanel", page_source)
        self.assertNotIn("生成预览", page_source)
        self.assertIn("校验项目", page_source)
        self.assertIn("导出可编辑版", page_source)
        self.assertIn("导出最终版", page_source)

    def test_technical_filters_drive_visible_evidence_images(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")
        evidence_source = (FRONTEND_SRC / "components" / "EvidencePanel.tsx").read_text(encoding="utf-8")

        self.assertIn("export type EvidenceImageFilterState", table_source)
        self.assertIn("onVisibleEvidenceFilterChange", table_source)
        self.assertIn("technicalUnitFilter", table_source)
        self.assertIn("technicalObjectFilter", table_source)
        self.assertIn("technical-filter-controls", table_source)
        self.assertIn("测评单元筛选", table_source)
        self.assertIn("测评对象筛选", table_source)
        self.assertIn("function referencedEvidenceImageIds", table_source)
        self.assertIn("const filterActive = Boolean(activeSubsystemName || activeUnitFilter || activeObjectFilter)", table_source)
        self.assertIn("imageIds: filterActive ? visibleEvidenceImageIds : []", table_source)

        self.assertIn("type EvidenceImageFilterBySection", page_source)
        self.assertIn("const [evidenceFilterBySection", page_source)
        self.assertIn("handleEvidenceFilterChange", page_source)
        self.assertIn("onVisibleEvidenceFilterChange={(filter) => handleEvidenceFilterChange(activeCode, filter)}", page_source)
        self.assertIn("visibleImageIds={activeEvidenceFilter?.imageIds}", page_source)
        self.assertIn("filterActive={activeEvidenceFilter?.active ?? false}", page_source)

        self.assertIn("visibleImageIds?: number[]", evidence_source)
        self.assertIn("filterActive?: boolean", evidence_source)
        self.assertIn("const visibleImageIdSet", evidence_source)
        self.assertIn("const displayImages = filterActive", evidence_source)
        self.assertIn("images.filter((image) => visibleImageIdSet.has(image.id))", evidence_source)
        self.assertIn("warningCount = displayImages.reduce", evidence_source)
        self.assertIn("图片 {displayImages.length}", evidence_source)
        self.assertIn("共 {images.length}", evidence_source)
        self.assertIn("disabled={filterActive || index === 0}", evidence_source)
        self.assertIn("当前筛选条件下没有被引用的证据图片。", evidence_source)

    def test_evidence_panel_displays_project_local_image_number(self) -> None:
        client_source = (FRONTEND_SRC / "api" / "client.ts").read_text(encoding="utf-8")
        evidence_source = (FRONTEND_SRC / "components" / "EvidencePanel.tsx").read_text(encoding="utf-8")

        self.assertIn("project_image_no?: number | null;", client_source)
        self.assertIn("项目图片", evidence_source)
        self.assertIn("image.project_image_no", evidence_source)
        self.assertIn("type EvidenceImagesChangeContext", evidence_source)
        self.assertIn("deletedImage?: EvidenceImage", evidence_source)
        self.assertIn("deletedImage: image", evidence_source)
        self.assertIn("image.figure_label ?? `${sectionCode}-${index + 1}`", evidence_source)
        self.assertIn("项目图片 {image.project_image_no ?? globalIndex + 1}", evidence_source)
        self.assertNotIn("图片ID", evidence_source)

    def test_project_page_reindexes_cached_project_images_and_references_after_delete(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")

        self.assertIn("function reindexCachedProjectImageNumbersAfterDelete", page_source)
        self.assertIn("details: Record<string, SectionDetail>", page_source)
        self.assertIn("const deletedProjectImageNo = deletedImage.project_image_no", page_source)
        self.assertIn("Object.entries(details).map", page_source)
        self.assertIn("evidence_images: detail.evidence_images.map((image, index)", page_source)
        self.assertIn("const nextProjectImageNo =", page_source)
        self.assertIn(": image.project_image_no - 1", page_source)
        self.assertIn("project_image_no: nextProjectImageNo", page_source)
        self.assertIn("figure_label: `图${code}-${index + 1}`", page_source)
        self.assertIn("sort_order: index + 1", page_source)
        self.assertIn("function removeDeletedImageReferencesFromRows", page_source)
        self.assertIn("const deletedToken = `[[FIG:${deletedImage.id}]]`", page_source)
        self.assertIn("row.record_text.includes(deletedToken)", page_source)
        self.assertIn("row.record_text.includes(deletedFigureLabel)", page_source)
        self.assertIn("reference.target_image_id === deletedImage.id", page_source)
        self.assertIn("reference.token === deletedToken", page_source)
        self.assertIn("const deletedImage = context?.deletedImage", page_source)
        self.assertIn("removeDeletedImageReferencesFromRows(rows, deletedImage)", page_source)
        self.assertIn("rowsContainDeletedImageReference(rows, deletedImage)", page_source)
        self.assertIn("context?.deletedImage", page_source)
        self.assertIn("reindexCachedProjectImageNumbersAfterDelete(nextDetails, deletedImage)", page_source)
        self.assertIn("onImagesChange={(images, context) => handleImagesChange(activeCode, images, context)}", page_source)

    def test_assessment_table_prefers_live_figure_label_over_stored_reference_display_text(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")

        self.assertIn("const displayText = existing?.displayText ?? token;", table_source)
        self.assertIn("displayText: displayText || token", table_source)
        self.assertIn("target_image_id: existing?.target_image_id ?? null", table_source)
        self.assertIn("const resolvedTargetImageId = reference ? reference.target_image_id : null;", table_source)
        self.assertIn("target_image_id: resolvedTargetImageId", table_source)
        self.assertNotIn("const fallbackDisplayText", table_source)
        self.assertNotIn("target_image_id: reference.target_image_id ?? existing?.target_image_id ?? null", table_source)
        self.assertNotIn("reference.display_text?.trim() || existing?.displayText || token", table_source)

    def test_assessment_table_uses_split_record_and_score_template_slots(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")

        self.assertIn("RecordTemplateSlot", table_source)
        self.assertIn("templateSlotsForUnit", table_source)
        self.assertIn("verificationTemplateSlots", table_source)
        self.assertIn("scoreBasisTemplateSlots", table_source)
        self.assertIn("replaceRecordTemplateSection", table_source)
        self.assertIn("extractTemplateSectionText", table_source)
        self.assertIn("测评验证记录：", table_source)
        self.assertIn("测评对象评分计算依据：", table_source)
        self.assertIn("templateSlotOptionLabel", table_source)
        self.assertIn("calculateTechnicalUnitScore", table_source)
        self.assertIn("formatScoreToFourDecimals", table_source)
        self.assertIn("formatObjectScore", table_source)
        self.assertIn("function displayRecordText", table_source)
        self.assertIn("function storedRecordText", table_source)
        self.assertIn("function crossReferencesForRecordText", table_source)
        self.assertIn("const recordDisplayText = displayRecordText(row, evidenceImages, sectionCode, profile)", table_source)
        self.assertIn("value={recordDisplayText}", table_source)
        self.assertIn("const recordText = storedRecordText(event.target.value, row, evidenceImages, sectionCode, profile)", table_source)
        self.assertIn("record_text: recordText", table_source)
        self.assertIn("cross_references: crossReferencesForRecordText(", table_source)
        self.assertIn("const displayRecordTextValue = insertAtSelectionOrPlaceholder(", table_source)
        self.assertNotIn("const recordText = insertAtSelectionOrPlaceholder(row.record_text, token", table_source)
        self.assertIn("onBlur={() => formatObjectScore(index)}", table_source)
        self.assertIn("function addTechnicalSectionObject", table_source)
        self.assertIn("function removeTechnicalSectionObject", table_source)
        self.assertIn("technicalObjectNames", table_source)
        self.assertIn("save-action-row", table_source)
        self.assertIn("toolbar-object-add", table_source)
        self.assertIn("A4_OBJECT_CATEGORIES", table_source)
        self.assertIn("对象分类", table_source)
        self.assertIn("重要数据传输机密性", table_source)
        self.assertIn("重要数据传输完整性", table_source)
        self.assertIn("重要数据存储机密性", table_source)
        self.assertIn("重要数据存储完整性", table_source)
        self.assertIn("重要信息资源安全标记完整性", table_source)
        self.assertIn("targetUnitsForTechnicalObject", table_source)
        self.assertIn("isA4UnitScopedObjectUnit", table_source)
        self.assertIn("canAddObjectWithinUnit(sectionCode, group.unit, technical)", table_source)
        self.assertIn("onClick={() => removeRow(index)}", table_source)
        self.assertNotIn("deleteWholeObject ? removeTechnicalSectionObject(row.object_name) : removeRow(index)", table_source)
        self.assertIn("technical-object-toolbar", table_source)
        self.assertIn("technical-object-list", table_source)
        self.assertIn("object-delete-button", table_source)
        self.assertIn("SUBSYSTEM_SECTION_CODES", table_source)
        self.assertIn("supportsSubsystem(sectionCode)", table_source)
        self.assertIn("subsystem-filter", table_source)
        self.assertIn("technical-entry-row", table_source)
        self.assertIn("function addSubsystem", table_source)
        self.assertIn("function removeSubsystem", table_source)
        self.assertIn("function assignUnassignedObjectsToSubsystem", table_source)
        self.assertIn("function removeObjectFromActiveSubsystem", table_source)
        self.assertIn("const technicalObjectEntries", table_source)
        self.assertIn("objectSubsystemNames.length === 1", table_source)
        self.assertIn("unassignedTechnicalObjectNames", table_source)
        self.assertIn("unassigned-object-list", table_source)
        self.assertIn("归入当前子系统", table_source)
        self.assertIn("全部归入当前子系统", table_source)
        self.assertIn("移出当前子系统", table_source)
        self.assertIn("row.subsystem", table_source)
        self.assertIn("subsystem: activeSubsystemName", table_source)
        self.assertIn("object_name: objectName", table_source)
        self.assertIn("row.subsystem?.trim() !== activeSubsystemName", table_source)
        self.assertIn("row.subsystem?.trim() === activeSubsystemName", table_source)
        self.assertIn("removeTechnicalSectionObject(objectName)", table_source)
        self.assertIn("onClick={() => removeObjectFromActiveSubsystem(objectName, targetSubsystemName)}", table_source)
        self.assertNotIn("{sectionSupportsSubsystem && activeSubsystemName ? (", table_source)
        self.assertIn("测评对象 {objectCount}", table_source)
        self.assertIn("canAddObjectWithinUnit(sectionCode, group.unit, technical)", table_source)
        self.assertNotIn("deleteEvidence", table_source)
        self.assertIn("applyCalculatedUnitScores", table_source)
        self.assertIn("updateUnitScoreForUnit", table_source)
        self.assertIn("unit-score-cell", table_source)
        self.assertIn("rowSpan={group.entries.length}", table_source)
        self.assertIn("分段模板", table_source)
        self.assertIn("套用验证记录模板", table_source)
        self.assertIn("套用评分依据模板", table_source)
        self.assertIn("template_group === \"verification_record\"", table_source)
        self.assertIn("template_group === \"score_basis\"", table_source)
        self.assertNotIn("record_text: slot.record_text", table_source)
        self.assertNotIn("recordTemplates", table_source)
        self.assertNotIn("optgroup", table_source)
        self.assertNotIn("onSaveRowAsTemplate", table_source)

    def test_assessment_table_previews_evidence_image_when_hovering_reference_label(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")
        styles_source = (FRONTEND_SRC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("type FigureReferenceHoverPreview", table_source)
        self.assertIn("function hoveredFigureReferenceFromTextarea", table_source)
        self.assertIn("function recordFigureReferenceItems", table_source)
        self.assertIn("function recordFigureReferenceParts", table_source)
        self.assertIn("const [figureHoverPreview", table_source)
        self.assertIn("record-textarea-shell", table_source)
        self.assertIn("record-reference-overlay", table_source)
        self.assertIn("record-reference-hotspot", table_source)
        self.assertIn("onMouseMove={(event) => handleRecordReferenceHover(event, row)}", table_source)
        self.assertIn("onMouseLeave={() => setFigureHoverPreview(null)}", table_source)
        self.assertIn("figure-hover-preview", table_source)
        self.assertIn("figure-hover-preview", styles_source)
        self.assertIn("record-reference-overlay", styles_source)
        self.assertIn("pointer-events: auto", styles_source)
        self.assertIn("position: fixed", styles_source)
        self.assertIn("left: 16px", styles_source)
        self.assertIn("const previewHeight = 480", table_source)
        self.assertIn("width: min(420px, calc(100vw - 32px))", styles_source)
        self.assertIn("max-height: 360px", styles_source)

    def test_assessment_table_supports_inline_evidence_upload(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")
        styles_source = (FRONTEND_SRC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("onUploadEvidenceImages", table_source)
        self.assertIn("inline-image-upload-button", table_source)
        self.assertIn("accept=\"image/png,image/jpeg\"", table_source)
        self.assertIn("multiple", table_source)
        self.assertIn("uploadPastedEvidenceImages", table_source)
        self.assertIn("pastedImageUploadDialog", table_source)
        self.assertIn("pendingPastedImageUpload", table_source)
        self.assertIn("confirmPastedImageUpload", table_source)
        self.assertIn("cancelPastedImageUpload", table_source)
        self.assertIn("粘贴截图题注", table_source)
        self.assertIn("图片题注", table_source)
        self.assertIn("caption?: string", table_source)
        self.assertIn("onUploadEvidenceImages(selectedFiles, { caption })", table_source)
        self.assertIn("clipboardImageFiles", table_source)
        self.assertIn("clipboardData.items", table_source)
        self.assertIn("insertReferenceImages", table_source)
        self.assertIn("onPaste={(event) => void uploadPastedEvidenceImages(index, event)}", table_source)
        self.assertIn("handleInlineEvidenceUpload", page_source)
        self.assertIn("uploadEvidenceImages(project.id", page_source)
        self.assertIn("caption: options?.caption", page_source)
        self.assertIn("onUploadEvidenceImages={(files, options) => handleInlineEvidenceUpload(activeCode, files, options)}", page_source)
        self.assertIn("return uploaded", page_source)
        self.assertIn(".inline-image-upload-button", styles_source)
        self.assertIn(".pasted-image-upload-backdrop", styles_source)
        self.assertIn(".pasted-image-upload-dialog", styles_source)
        self.assertIn("background: var(--color-primary-hover)", styles_source)
        self.assertNotIn("--color-primary-dark", styles_source)
        self.assertNotIn("--color-primary-muted", styles_source)

    def test_assessment_table_auto_sizes_record_textareas(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")
        styles_source = (FRONTEND_SRC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("const RECORD_TEXTAREA_MIN_HEIGHT = 126", table_source)
        self.assertIn("function autoSizeRecordTextarea", table_source)
        self.assertIn("textarea.style.height = \"auto\"", table_source)
        self.assertIn("Math.max(RECORD_TEXTAREA_MIN_HEIGHT, textarea.scrollHeight)", table_source)
        self.assertIn("recordTextareaRefs", table_source)
        self.assertIn("recordTextareaRefs.current[index] = node", table_source)
        self.assertIn("onInput={(event) => autoSizeRecordTextarea(event.currentTarget)}", table_source)
        self.assertIn("autoSizeRecordTextareas", table_source)
        self.assertIn("overflow: hidden", styles_source)

    def test_subsystem_sections_hide_assigned_object_list(self) -> None:
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")

        self.assertIn("const shouldShowTechnicalObjectList = technical && !sectionSupportsSubsystem", table_source)
        self.assertIn("{shouldShowTechnicalObjectList && technicalObjectEntries.length > 0 ? (", table_source)
        self.assertIn("{shouldShowTechnicalObjectList && technicalObjectEntries.length === 0 ? (", table_source)
        self.assertIn("unassignedTechnicalObjectNames.length > 0", table_source)
        self.assertNotIn("{technicalObjectEntries.length > 0 ? (", table_source)

    def test_project_page_supports_editor_undo_stack(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")

        self.assertIn("const MIN_UNDO_STEPS = 5", page_source)
        self.assertIn("const MAX_UNDO_STEPS = 20", page_source)
        self.assertIn("type UndoSnapshot", page_source)
        self.assertIn("const [undoStack", page_source)
        self.assertIn("function createUndoSnapshot", page_source)
        self.assertIn("function pushUndoSnapshot", page_source)
        self.assertIn("function restoreUndoSnapshot", page_source)
        self.assertIn("function handleUndo", page_source)
        self.assertIn("function isUndoShortcutTarget", page_source)
        self.assertIn("event.key.toLowerCase() === \"z\"", page_source)
        self.assertIn("event.ctrlKey || event.metaKey", page_source)
        self.assertIn("pushUndoSnapshot()", page_source)
        self.assertIn("onClick={handleUndo}", page_source)
        self.assertIn("disabled={undoStack.length === 0 || isSavingAny}", page_source)

    def test_evidence_panel_opens_fullscreen_image_preview(self) -> None:
        evidence_source = (FRONTEND_SRC / "components" / "EvidencePanel.tsx").read_text(encoding="utf-8")
        styles_source = (FRONTEND_SRC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("const [selectedPreviewImage", evidence_source)
        self.assertIn("setSelectedPreviewImage(image)", evidence_source)
        self.assertIn("event.key === \"Escape\"", evidence_source)
        self.assertIn("image-preview-button", evidence_source)
        self.assertIn("image-lightbox", evidence_source)
        self.assertIn("role=\"dialog\"", evidence_source)
        self.assertIn("aria-modal=\"true\"", evidence_source)
        self.assertIn("onClick={() => setSelectedPreviewImage(null)}", evidence_source)
        self.assertIn("onClick={(event) => event.stopPropagation()}", evidence_source)

        self.assertIn(".image-preview-button", styles_source)
        self.assertIn("cursor: zoom-in", styles_source)
        self.assertIn(".image-lightbox", styles_source)
        self.assertIn("position: fixed", styles_source)
        self.assertIn("inset: 0", styles_source)
        self.assertIn(".image-lightbox-image", styles_source)
        self.assertIn("max-height: calc(100vh - 180px)", styles_source)

    def test_template_manager_is_fixed_split_slot_editor_with_config_backup(self) -> None:
        panel_source = (FRONTEND_SRC / "components" / "TemplateManagerPanel.tsx").read_text(encoding="utf-8")

        self.assertIn("recordTemplateSlots", panel_source)
        self.assertIn("TEMPLATE_GROUP_ORDER", panel_source)
        self.assertIn("slotsByTemplateGroup", panel_source)
        self.assertIn("template_group_label", panel_source)
        self.assertIn("onUpdateSlot", panel_source)
        self.assertIn("onResetSlot", panel_source)
        self.assertIn("onExportSlots", panel_source)
        self.assertIn("onPreviewImportSlots", panel_source)
        self.assertIn("onImportSlots", panel_source)
        self.assertIn("每个单元 2 组 / 6 模板", panel_source)
        self.assertIn("测评验证记录模板", panel_source)
        self.assertIn("测评对象评分计算依据模板", panel_source)
        self.assertIn("恢复默认", panel_source)
        self.assertIn("分段模板配置导入导出", panel_source)
        self.assertIn("导出模板配置", panel_source)
        self.assertIn("选择配置 JSON", panel_source)
        self.assertIn("预览导入", panel_source)
        self.assertIn("确认导入", panel_source)
        self.assertNotIn("onCreate", panel_source)
        self.assertNotIn("onDelete", panel_source)
        self.assertNotIn("onCopy", panel_source)
        self.assertNotIn("onSaveRowAsTemplate", panel_source)
        self.assertNotIn("source_type", panel_source)
        self.assertNotIn("新建模板", panel_source)
        self.assertNotIn("删除", panel_source)
        self.assertNotIn("复制", panel_source)
        self.assertNotIn("我的模板", panel_source)


    def test_subsystem_state_is_preserved_above_assessment_table(self) -> None:
        page_source = (FRONTEND_SRC / "pages" / "ProjectPage.tsx").read_text(encoding="utf-8")
        table_source = (FRONTEND_SRC / "components" / "AssessmentTable.tsx").read_text(encoding="utf-8")

        self.assertIn("subsystemUiStateBySection", page_source)
        self.assertIn("setSubsystemUiStateBySection", page_source)
        self.assertIn("subsystemUiState={subsystemUiStateBySection[activeCode] ?? EMPTY_SUBSYSTEM_UI_STATE}", page_source)
        self.assertIn("handleSubsystemUiStateChange(activeCode, updater, options)", page_source)
        self.assertIn("options.dirty", page_source)
        self.assertIn("subsystemUiState", table_source)
        self.assertIn("onSubsystemUiStateChange", table_source)
        self.assertIn("setManualSubsystemNamesForSection", table_source)
        self.assertIn("setActiveSubsystemForSection", table_source)
        self.assertNotIn("setManualSubsystemNames([]);", table_source)
        self.assertNotIn("setActiveSubsystem(\"\");", table_source)

    def test_subsystem_and_object_controls_share_one_grid_row(self) -> None:
        styles_source = (ROOT / "frontend" / "src" / "styles.css").read_text(encoding="utf-8")

        self.assertIn(".technical-entry-row.with-subsystem", styles_source)
        self.assertIn("grid-template-columns: minmax(140px, 1.1fr) auto minmax(140px, 1fr) minmax(110px, 0.8fr) minmax(140px, 1fr) auto", styles_source)
        self.assertIn(".technical-entry-row.with-subsystem .subsystem-controls", styles_source)
        self.assertIn(".technical-entry-row.with-subsystem .technical-object-add", styles_source)
        self.assertIn("display: contents", styles_source)


if __name__ == "__main__":
    unittest.main()
